version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: impercap_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data_impercap:/var/opt/mssql
    networks:
      - productnetwork

  # Serviço do Back-end
  back-end: 
    build:
      context: ./back-end  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING_DOCKER}
    depends_on:
      - sqlserver
    networks:
      - productnetwork
    restart: on-failure

networks:
  productnetwork:

volumes:
  sql_data_impercap: