version: '3.8'

services:
  back-end: 
    build:
      context: ./back-end  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tcp:serve-impercap.database.windows.net,1433;Database=impercap;User ID=admimpercap;Password=banco2025#2@;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    networks:
      - productnetwork
    restart: on-failure

networks:
  productnetwork: