services:
  back-end: 
    build:
      context: ./back-end  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Impercap2025
    ports:
      - "1433:1433"
    volumes:
      - sql_data_impercap:/var/opt/mssql
    networks:
      - productnetwork

networks:
  productnetwork:

volumes:
  sql_data_impercap: